### ISSUE TITLE
Composer autoload errors

### ISSUE THREAD

**Issue by hostep** [SendCloud/sendcloud#135]
Hi

Using
- version 2.0.3 of your module
- composer version 2.3.5 or higher

Composer throws these errors when dumping an optimised autoloader:

```
$ composer dump-autoload --optimize
...
Class SendCloud\SendCloud\Model\ResourceModel\SendclooudDeliveryZone\Collection located in ./vendor/sendcloud/sendcloud/Model/ResourceModel/AbstractDomen/Collection.php does not comply with psr-4 autoloading standard. Skipping.
Class SendCloud\SendCloud\Controller\Adminhtml\System\Config\Save located in ./vendor/sendcloud/sendcloud/Controller/Adminhtml/Sysytem/Config/Save.php does not comply with psr-4 autoloading standard. Skipping.
...
```

It looks like there might be some typo's in the filenames or namespaces. For example the namespace `SendclooudDeliveryZone`  is incorrect, it should be `AbstractDomen` [over here](https://github.com/SendCloud/sendcloud/blob/2.0.3/Model/ResourceModel/AbstractDomen/Collection.php#L3), and the [directory name `Sysytem`](https://github.com/SendCloud/sendcloud/tree/2.0.3/Controller/Adminhtml) should be changed to `System`.

(If you run Magento in developer mode and want to test changes you make to those files, make sure to dump the autoload again **without** optimisation, because it will cause problems otherwise: `composer dump-autoload`, the optimised autoloader is only useful for Magento in production mode)

Thanks!

**Comment by ivabocheva** [comment]
Hi hostep, 

Thank you for your comment, we are currently reviewing it. 

Kind regards,

The Sendcloud team

**Comment by teodoratimoti** [comment]
Hi hostep,

Please note that our team found what the issue is and we fixed it.

The new version 2.0.4 is released on both marketplace and GitHub.

Thank you,

Best regards.

**Comment by hostep** [comment]
Hi @teodoratimoti

I'm afraid it's not fully fixed, I still get the following with version 2.0.4:

```
$ composer dump-autoload --optimize
...
Class SendCloud\SendCloud\Controller\Adminhtml\System\Config\Save located in ./vendor/sendcloud/sendcloud/Controller/Adminhtml/Sysytem/Config/Save.php does not comply with psr-4 autoloading standard. Skipping.
...
```

It looks like the directory `Controller/Adminhtml/Sysytem` was forgotten to be removed...


Also additionally, I'm very confused about the large amount of [changes between 2.0.3 and 2.0.4](https://github.com/SendCloud/sendcloud/compare/2.0.3...2.0.4?w=1), these weren't needed:
- php coding standards suggest to put the `{` on a new line after a method, for some reason you changed it?
- the syntax for arrays was changed in PHP 5.4 to allow for the simpler `[]` syntax intead of `array()`, but you changed it back to the old syntax from the year 2011/2012?

What were the reasons for these changes? In my opinion these should be reverted again... But that's just a suggestion.
